knpu_oauth2_client:
    clients:
        custom:
            type: generic
            client_id: '%env(OAUTH_CLIENT_ID)%'
            client_secret: '%env(OAUTH_CLIENT_SECRET)%'
            redirect_route: connect_custom_check
            redirect_params: {}
            provider_class: 'League\OAuth2\Client\Provider\GenericProvider'
            provider_options:
                urlAuthorize: 'https://your-oauth-server.com/authorize'
                urlAccessToken: 'https://your-oauth-server.com/token'
                urlResourceOwnerDetails: 'https://your-oauth-server.com/resource'
