nelmio_api_doc:
    documentation:
        info:
            title: PHP Repository API Searcher
            description: API to search for  repositories on GitHub
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
